### PR TITLE
Make the box-sizing explicit on the MoonLoader circle

### PR DESCRIPTION
**Pull request by maco**
Recent versions of Tailwind CSS force everything to `box-sizing: border-box;`
(see https://github.com/tailwindcss/tailwindcss/pull/1111 )
Tailwind isn't the only thing out there using that hack, so this is sure to be a wider-ranging problem.
The result of using Tailwind & react-spinners in the same project without this change is that the spinner circle wobbles around.

### CODE REVIEW

**Comment by davidhu2000** [comment]
hi @maco, what effect does adding this have on the loader when `tailwindcss` isn't used?

**Comment by maco** [comment]
Content-box is the default in all non-Microsoft browsers and in Microsoft
ones after…IE9, IIRC. Your code expects the browsers to be doing their
default thing. Tailwind is behaving like a reset rule.
-- 
Mackenzie Morgan
(she/her)

**Comment by davidhu2000** [comment]
ah i see. @maco thanks for the change. I'll review once i get a chance to. Can you also update snapshots? Otherwise the tests will fail.

**Comment by stan-sack** [comment]
would love to see this in master. You cant override this using the override method from the docs so it becomes troublesome to fix. Right now im using a css wildcard which is far less than ideal:
```
[class*="css-"] {
    box-sizing: content-box;
}
```

**Comment by davidhu2000** [comment]
I checked out the changes. looks good for all browsers.

**Comment by davidhu2000** [comment]
This is released in `0.8.2`

**Pull request merged**
