### PR TITLE
Update peer dependencies to support React 19

### LINKED ISSUE #611: Update peer dependencies to support React 19
Currently we have:
```
  "peerDependencies": {
    "react": "^16.0.0 || ^17.0.0 || ^18.0.0",
    "react-dom": "^16.0.0 || ^17.0.0 || ^18.0.0"
  },
```

React 19 is currently in RC and release is around the corner.

Could we update the `react` peer dependencies to support `19.0.0`?

From my inspection, it doesn't look like this project using any functionality that will change / break from `18` to `19` so I believe the change can be made now.

Also I'm personally using this project on production with React 19 RC with no issues.

### PR DESCRIPTION
**Pull request by mobeigi**
# What changes are introduced?
Update peer dependencies to support React 19.

Fixes #611

### CODE REVIEW

**Comment by davidhu2000** [comment]
hey, @mobeigi thanks for the contribution. i'll be sure to get this out soon (before react 19 is out)

**Comment by davidhu2000** [comment]
looks like you need a `yarn install` to fix the tests

**Comment by tulir** [comment]
React 19 was just released: https://react.dev/blog/2024/12/05/react-19

**Comment by davidhu2000** [comment]
published at 0.15.0. Appreciate the contribution

**Pull request merged**
