### PR TITLE
Add emotion for fixing ssr issues

### PR DESCRIPTION
**Pull request by GuillaumeCisco**

### CODE REVIEW

**Comment by davidhu2000** [comment]
after making these changes, was webpack able to bundle up the loaders for the demo site? I tried your implementation with `BarLoader` but I got this error:

> Uncaught TypeError: Cannot read property 'apply' of undefined

**Comment by GuillaumeCisco** [comment]
hey @davidhu2000 , I've just updated the code for adding the missing babel plugins ;)

**Comment by davidhu2000** [comment]
@GuillaumeCisco everything seems to be working for the individual loaders. However, the demo site lost some functionality. I can unable to change the color and other attributes. Did this happen to you? Seems like this is the expected behavior for `emotion`.

**Comment by GuillaumeCisco** [comment]
Hi @davidhu2000, I've just updated the code for making emotion works correctly with recompose and updated render.
Also I've updated the form creation file for handling the `margin` field which should be a string and not a number.

**Pull request merged**
