### PR TITLE
Refacto update

### LINKED ISSUE #36: Problem with MoonLoader
The whole body is rotating together with the little thing lol. please fix this I like the moon loader above all.
Moonloader bug

### PR DESCRIPTION
**Pull request by GuillaumeCisco**
Big refactoring - Fix #36 #35 #29 #23 #2
Add `className` property for overriding loader style.
Fix scalibility pacman loader.
Load spinner like lodash do : `import {BarLoader} from 'react-spinners` or `import BarLoader from 'react-spinners/BarLoader'`

### CODE REVIEW

**Comment by davidhu2000** [comment]
Thanks @GuillaumeCisco, quick question, with the new updated import, does it allow both
 
```
import { Barloader } from 'react-spinners';
import BarLoader from 'react-spinners/BarLoader';
```

**Comment by GuillaumeCisco** [comment]
Yes

--
Guillaume Cisco

**Comment by davidhu2000** [comment]
@GuillaumeCisco looks like merging #34 caused a ton of merge conflicts.

**Comment by GuillaumeCisco** [comment]
@davidhu2000 Yes I saw something like this.
Using a new defined `loaderStyle` is over-killing. As we use `emotion`, the simplest and proper way is to stick with `emotion` api. Using `className` is easy, scalable, maintainable because it is a fundamental part of `emotion`.

Simply passing your css style overriding everything is far more easier and understandable without learning a new prop.

README should be updated too, in order to show a example.

**Comment by ludovicofischer** [comment]
Hi, I’m also interested in importing Spinners one at a time. Could we leave `loaderStyle` vs `className` aside for the moment and try to merge the file structure refactoring? I could prepare a new pull request based on this one but without touching `loaderStyle`.

**Comment by GuillaumeCisco** [comment]
@ludovicofischer @davidhu2000 
I've just updated the code for solving conflicts and removing `loaderStyle`

**Comment by ludovicofischer** [comment]
Great! But technically the next release becomes  breaking now. I don’t use `loaderStyle` so I don’t care  and according to [semver](https://semver.org/), when the major version is 0 anyone should expect breakage at any moment, but it could annoy someone out there. I guess @davidhu2000 can decide.

**Comment by GuillaumeCisco** [comment]
@ludovicofischer , yes absolutely.

**Comment by davidhu2000** [comment]
This is definitely at least a minor version bump, may have to deprecate `0.3.3`

**Pull request merged**
